# Generated by Django 4.0.7 on 2024-09-05 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('BIN', 'Batch Invitation'), ('EIN', 'Exam Invitation'), ('EAS', 'Exam Assignment')], max_length=3, verbose_name='Email type')),
                ('message_id', models.CharField(max_length=50, verbose_name='Message id')),
                ('status', models.CharField(choices=[('sent', 'Sent from the backed.'), ('accepted', 'Tracking Accepted'), ('clicked', 'Tracking Clicks'), ('complained', 'Tracking Spam Complaints'), ('delivered', 'Tracking Deliveries'), ('opened', 'Tracking Opens'), ('permanent_fail', 'Tracking Failures'), ('temporary_fail', 'Tracking Failures'), ('unsubscribed', 'Open and Click Bot Detection')], default='sent', max_length=20, verbose_name='Status')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('from_email', models.CharField(max_length=200, verbose_name='From email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('mailgun_response', models.JSONField(blank=True, null=True, verbose_name='Mailgun response')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(max_length=2048)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('S', 'Sent'), ('R', 'Read'), ('U', 'Unread')], default='CR', max_length=5, verbose_name='Status')),
                ('notification_type', models.CharField(choices=[('AR', 'Approval Request'), ('RA', 'Report Available')], max_length=5, verbose_name='NotificationType')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('recipients', models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
