# Generated by Django 4.0.7 on 2024-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedocument',
            name='status',
            field=models.CharField(choices=[('S', 'Saved'), ('AR', 'Approval Requested'), ('A', 'Approved'), ('R', 'Rejected')], default='S', max_length=50, verbose_name='Status'),
        ),
    ]
