# Generated by Django 4.0.7 on 2024-09-22 02:29

import catalog.models
import collections
from django.db import migrations, models
import django.db.models.deletion
import utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_certificatedocument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Manufacturer Name')),
                ('brand_name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('ingredients', models.TextField(help_text='Enter ingredients', max_length=1000)),
                ('annual_production_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Annual Production Size')),
                ('quantity_available_per_month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity Available Per Month')),
                ('lead_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lead Time')),
                ('quantity_available_today', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity Available Today')),
                ('incoterms', models.CharField(blank=True, max_length=50, null=True, verbose_name='Incoterms')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('description', models.TextField(help_text='Enter description', max_length=1000)),
                ('advance_payment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Advance Payment')),
                ('shelf_life', models.IntegerField(blank=True, null=True, verbose_name='Shelf Life in days')),
                ('packaging_details', models.TextField(blank=True, help_text='Packaging details', max_length=1000, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Grade')),
                ('bar_code', models.CharField(max_length=20, verbose_name='Bar Code')),
                ('bar_code_type', models.CharField(choices=[('UPC', 'Universal Product Code'), ('EAN', 'European Article Number'), ('GS1', 'GS1 DataBar'), ('QR', 'QR Codes'), ('C128', 'Code 128'), ('ITF14', 'ITF-14')], max_length=5, verbose_name='Bar Code Type')),
                ('additional_data', models.JSONField(blank=True, default=collections.OrderedDict, null=True)),
                ('is_private_label_available', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='catalog.category')),
                ('certificates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.certificatedocument')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAndOrdering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_the_box', models.CharField(max_length=50, verbose_name='Quantity in the box')),
                ('payment_terms', models.TextField(max_length=1000, verbose_name='Payment terms')),
                ('moq', models.CharField(blank=True, max_length=50, null=True, verbose_name='MOQ per Month')),
                ('ltl_available', models.BooleanField(default=False)),
                ('lead_time_first_shipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lead Time First Shipment')),
                ('annual_production', models.CharField(blank=True, max_length=50, null=True, verbose_name='Annual Production')),
                ('min_no_boxes_pallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Min No of boxes on pallet')),
                ('max_no_boxes_pallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Max No of boxes on pallet')),
                ('max_no_items_in_full_40_inch_container', models.CharField(blank=True, max_length=50, null=True, verbose_name='Max no of boxes in full 40 inch container')),
                ('shipment_terms', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipment terms')),
                ('shipping_modes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipment Modes')),
                ('types_of_pallets_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='Types of Pallets used')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_weight_per_volume', models.CharField(max_length=20, verbose_name='Net Weight/Volume')),
                ('gross_weight_per_volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gross Weight/Volume')),
                ('quantity_per_carton', models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantity/Carton')),
                ('quantity_of_items_per_pallete', models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantity/allete')),
                ('volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Volume')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer Name')),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer Name')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.helpers.catalog_directory_path, validators=[catalog.models.verify_product_image_mime_type, catalog.models.verify_product_image_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_stock', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
