# Generated by Django 4.0.7 on 2024-09-05 06:17

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Name')),
                ('description', models.TextField(blank=True, help_text='Enter description', max_length=1000, null=True)),
                ('advance_payment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Advance Payment')),
                ('weight_per_volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Weight/Volume')),
                ('shelf_life', models.IntegerField(blank=True, null=True, verbose_name='Shelf Life in days')),
                ('packaging_details', models.TextField(blank=True, help_text='Packaging details', max_length=1000, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Grade')),
                ('bar_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bar Code')),
                ('bar_code_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bar Code Type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='catalog.category')),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.certificatedocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer Name')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer Name')),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAndOrdering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moq', models.CharField(max_length=50, verbose_name='MOQ per Month')),
                ('max_size_first_shipment', models.CharField(max_length=50, verbose_name='Max Size First Shipment')),
                ('ltl_available', models.BooleanField(default=False)),
                ('lead_time_first_shipment', models.CharField(max_length=50, verbose_name='Lead Time First Shipment')),
                ('annual_production', models.CharField(max_length=50, verbose_name='Annual Production')),
                ('quantity_in_the_box', models.CharField(max_length=50, verbose_name='Quantity in the box')),
                ('min_no_boxes_pallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Min No of boxes on pallet')),
                ('max_no_boxes_pallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Max No of boxes on pallet')),
                ('max_no_items_in_full_40_inch_container', models.CharField(blank=True, max_length=50, null=True, verbose_name='Max no of boxes in full 40 inch container')),
                ('payment_terms', models.CharField(blank=True, choices=[('B', 'Batch'), ('E', 'Exam'), ('QP', 'Question_Paper')], max_length=100, null=True, verbose_name='Payment terms')),
                ('shipment_terms', models.CharField(blank=True, choices=[('P', 'Pending'), ('F', 'Failed'), ('D', 'Done')], max_length=100, null=True, verbose_name='Shipment terms')),
                ('shipping_modes', models.CharField(blank=True, choices=[('B', 'Batch'), ('E', 'Exam'), ('QP', 'Question_Paper')], max_length=100, null=True, verbose_name='Shipment Modes')),
                ('types_of_pallets_used', models.CharField(blank=True, choices=[('B', 'Batch'), ('E', 'Exam'), ('QP', 'Question_Paper')], max_length=100, null=True, verbose_name='Types of Pallets used')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[catalog.models.verify_product_image_mime_type, catalog.models.verify_product_image_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Manufacturer Name')),
                ('ingredients', models.TextField(blank=True, help_text='Enter ingredients', max_length=1000, null=True)),
                ('annual_production_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Annual Production Size')),
                ('quantity_available_per_month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity Available Per Month')),
                ('lead_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lead Time')),
                ('quantity_available_today', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity Available Today')),
                ('incoterms', models.CharField(blank=True, max_length=50, null=True, verbose_name='Incoterms')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
            ],
        ),
    ]
